--- #YAML:1.0
name:               WWW-RapidShare
version:            0.3.1
abstract:           Download files from Rapidshare
author:
    - Rohan Almeida <rohan@almeida.in>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:  0
    version:          0
    WWW::Mechanize:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
